import { clusters, items, sources } from "@/db/schema";

export const storySelectFields = {
  id: items.id,
  title: items.title,
  titleZh: items.titleZh,
  titleEn: items.titleEn,
  summaryZh: items.summaryZh,
  summaryEn: items.summaryEn,
  editorNoteZh: items.editorNoteZh,
  editorNoteEn: items.editorNoteEn,
  editorAnalysisZh: items.editorAnalysisZh,
  editorAnalysisEn: items.editorAnalysisEn,
  reasoning: items.reasoning,
  reasoningZh: items.reasoningZh,
  reasoningEn: items.reasoningEn,
  hkr: items.hkr,
  url: items.url,
  importance: items.importance,
  tier: items.tier,
  tags: items.tags,
  publishedAt: items.publishedAt,
  sourceId: items.sourceId,
  sourceNameZh: sources.nameZh,
  sourceNameEn: sources.nameEn,
  sourceLocale: sources.locale,
  sourceKind: sources.kind,
  sourceGroup: sources.group,
} as const;

export const eventStorySelectFields = {
  clusterId: items.clusterId,
  clusterMemberCount: clusters.memberCount,
  clusterFirstSeenAt: clusters.firstSeenAt,
  clusterLatestMemberAt: clusters.latestMemberAt,
  clusterCanonicalTitleZh: clusters.canonicalTitleZh,
  clusterCanonicalTitleEn: clusters.canonicalTitleEn,
  clusterEditorNoteZh: clusters.editorNoteZh,
  clusterEditorNoteEn: clusters.editorNoteEn,
  clusterEditorAnalysisZh: clusters.editorAnalysisZh,
  clusterEditorAnalysisEn: clusters.editorAnalysisEn,
  clusterImportance: clusters.importance,
  clusterEventTier: clusters.eventTier,
  clusterHkr: clusters.hkr,
} as const;
