import { DAILY_COLUMN_LOCALE } from "@/lib/types";

export const DAILY_COLUMN_INDEX_TAKE_MIN = 1;
export const DAILY_COLUMN_INDEX_TAKE_MAX = 180;
export const DEFAULT_DAILY_COLUMN_INDEX_TAKE = 30;
export const DEFAULT_DAILY_COLUMN_QUERY_LOCALE = DAILY_COLUMN_LOCALE;
