import type { Source } from "@/lib/types";

export const sourceCatalog: Source[] = [
  // ── Vendor official ─────────────────────────────────────────────
  {
    id: "anthropic-news",
    name: { en: "Anthropic News", zh: "Anthropic 官方动态" },
    url: "https://www.anthropic.com/news",
    kind: "scrape",
    group: "vendor-official",
    locale: "en",
    cadence: "daily",
    priority: 1,
    tags: ["Anthropic", "product", "research"],
    enabled: true,
  },
  {
    id: "openai-news",
    name: { en: "OpenAI Blog", zh: "OpenAI 博客" },
    url: "https://openai.com/news/rss.xml",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "daily",
    priority: 1,
    tags: ["OpenAI", "product", "research"],
    enabled: true,
  },
  {
    id: "google-deepmind",
    name: { en: "Google DeepMind Blog", zh: "DeepMind 博客" },
    url: "https://deepmind.google/discover/blog/rss.xml",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "weekly",
    priority: 1,
    tags: ["DeepMind", "research"],
    enabled: true,
  },
  {
    id: "google-research",
    name: { en: "Google Research Blog", zh: "Google 研究院" },
    url: "https://research.google/blog/rss/",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["Google", "research"],
    enabled: true,
  },
  {
    id: "meta-ai",
    name: { en: "Meta AI Blog", zh: "Meta AI 博客" },
    url: "https://ai.meta.com/blog/rss/",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["Meta", "research"],
    enabled: true,
  },
  {
    id: "microsoft-ai",
    name: { en: "Microsoft AI Blog", zh: "微软 AI 博客" },
    url: "https://blogs.microsoft.com/ai/feed/",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["Microsoft"],
    enabled: true,
  },
  {
    id: "nvidia-blog",
    name: { en: "NVIDIA Blog", zh: "NVIDIA 博客" },
    url: "https://blogs.nvidia.com/feed/",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["NVIDIA", "hardware"],
    enabled: true,
  },
  {
    id: "huggingface-blog",
    name: { en: "Hugging Face Blog", zh: "Hugging Face 博客" },
    url: "https://huggingface.co/blog/feed.xml",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["HuggingFace", "open-source"],
    enabled: true,
  },
  {
    id: "xiaomi-research",
    name: { en: "Xiaomi AI Lab", zh: "小米 AI 实验室" },
    url: "https://rsshub.app/xiaomi/ai",
    kind: "rsshub",
    group: "vendor-official",
    locale: "zh",
    cadence: "weekly",
    priority: 1,
    tags: ["小米", "model"],
    enabled: true,
  },
  {
    id: "deepseek-hf",
    name: { en: "DeepSeek (HuggingFace)", zh: "深度求索 (HF)" },
    url: "https://huggingface.co/deepseek-ai",
    kind: "scrape",
    group: "vendor-official",
    locale: "multi",
    cadence: "daily",
    priority: 1,
    tags: ["DeepSeek", "open-source"],
    enabled: true,
  },
  {
    id: "qwen-hf",
    name: { en: "Qwen (Alibaba)", zh: "通义千问" },
    url: "https://huggingface.co/Qwen",
    kind: "scrape",
    group: "vendor-official",
    locale: "multi",
    cadence: "daily",
    priority: 1,
    tags: ["Alibaba", "open-source"],
    enabled: true,
  },

  // ── Media ────────────────────────────────────────────────────────
  {
    id: "hn-frontpage",
    name: { en: "Hacker News Frontpage", zh: "Hacker News 首页" },
    url: "https://hnrss.org/frontpage",
    kind: "rss",
    group: "media",
    locale: "en",
    cadence: "hourly",
    priority: 1,
    tags: ["tech", "community"],
    enabled: true,
  },
  {
    id: "techcrunch-ai",
    name: { en: "TechCrunch AI", zh: "TechCrunch AI" },
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    kind: "rss",
    group: "media",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["news"],
    enabled: true,
  },
  {
    id: "verge-ai",
    name: { en: "The Verge · AI", zh: "The Verge · AI" },
    url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    kind: "rss",
    group: "media",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["news"],
    enabled: true,
  },
  {
    id: "mit-techreview",
    name: { en: "MIT Technology Review", zh: "MIT 科技评论" },
    url: "https://www.technologyreview.com/feed/",
    kind: "rss",
    group: "media",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["analysis"],
    enabled: true,
  },
  {
    id: "36kr-ai",
    name: { en: "36kr AI Channel", zh: "36 氪 · AI 频道" },
    url: "https://rsshub.app/36kr/news/35",
    kind: "rsshub",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 1,
    tags: ["news", "中文"],
    enabled: true,
  },
  {
    id: "huxiu-ai",
    name: { en: "Huxiu · AI", zh: "虎嗅 · AI" },
    url: "https://rsshub.app/huxiu/channel/ai",
    kind: "rsshub",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 2,
    tags: ["中文"],
    enabled: true,
  },
  {
    id: "sspai-matrix",
    name: { en: "Sspai Matrix", zh: "少数派 Matrix" },
    url: "https://rsshub.app/sspai/matrix",
    kind: "rsshub",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 2,
    tags: ["中文"],
    enabled: true,
  },
  {
    id: "jiqizhixin",
    name: { en: "Synced (jiqizhixin)", zh: "机器之心" },
    url: "https://rsshub.app/jiqizhixin",
    kind: "rsshub",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 1,
    tags: ["中文", "research"],
    enabled: true,
  },
  {
    id: "qbitai",
    name: { en: "QbitAI", zh: "量子位" },
    url: "https://rsshub.app/qbitai",
    kind: "rsshub",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 1,
    tags: ["中文"],
    enabled: true,
  },

  // ── Newsletter ──────────────────────────────────────────────────
  {
    id: "bensbites",
    name: { en: "Ben's Bites", zh: "Ben's Bites" },
    url: "https://www.bensbites.com/feed",
    kind: "rss",
    group: "newsletter",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["newsletter"],
    enabled: true,
  },
  {
    id: "thebatch",
    name: { en: "The Batch (Andrew Ng)", zh: "The Batch (吴恩达)" },
    url: "https://www.deeplearning.ai/the-batch/feed/",
    kind: "rss",
    group: "newsletter",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["newsletter"],
    enabled: true,
  },
  {
    id: "importai",
    name: { en: "Import AI (Jack Clark)", zh: "Import AI" },
    url: "https://jack-clark.net/feed/",
    kind: "rss",
    group: "newsletter",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["policy", "newsletter"],
    enabled: true,
  },

  // ── Research ────────────────────────────────────────────────────
  {
    id: "arxiv-cs-ai",
    name: { en: "arXiv · cs.AI", zh: "arXiv · cs.AI" },
    url: "http://export.arxiv.org/api/query?search_query=cat:cs.AI&sortBy=submittedDate&sortOrder=descending",
    kind: "atom",
    group: "research",
    locale: "en",
    cadence: "daily",
    priority: 1,
    tags: ["arxiv", "paper"],
    enabled: true,
  },
  {
    id: "arxiv-cs-cl",
    name: { en: "arXiv · cs.CL", zh: "arXiv · cs.CL" },
    url: "http://export.arxiv.org/api/query?search_query=cat:cs.CL&sortBy=submittedDate&sortOrder=descending",
    kind: "atom",
    group: "research",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["arxiv", "nlp"],
    enabled: true,
  },
  {
    id: "huggingface-papers",
    name: { en: "HuggingFace Papers", zh: "HuggingFace 每日论文" },
    url: "https://huggingface.co/papers",
    kind: "scrape",
    group: "research",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["paper", "digest"],
    enabled: true,
  },
  {
    id: "paperswithcode",
    name: { en: "Papers With Code Trending", zh: "Papers With Code 热门" },
    url: "https://paperswithcode.com/latest",
    kind: "scrape",
    group: "research",
    locale: "en",
    cadence: "daily",
    priority: 3,
    tags: ["paper"],
    enabled: false,
  },

  // ── Social ───────────────────────────────────────────────────────
  // ── X (Twitter) — pay-per-tweet via X API v2, one source per handle so
  //    each account gets its own health + since_id cursor. Hourly cadence
  //    with max_results=20 keeps monthly tweet-read cost well under the free
  //    tier's 10k/month ceiling per-handle.
  {
    id: "x-dotey",
    name: { en: "X · @dotey", zh: "X · @dotey（宝玉）" },
    url: "https://x.com/dotey",
    kind: "x-api",
    group: "social",
    locale: "zh",
    cadence: "hourly",
    priority: 2,
    tags: ["X", "twitter", "chinese-ai"],
    enabled: true,
    notes: "宝玉 — 资深 AI 工程师、翻译家、博主",
  },
  {
    id: "x-khazix",
    name: { en: "X · @Khazix0918", zh: "X · @Khazix0918" },
    url: "https://x.com/Khazix0918",
    kind: "x-api",
    group: "social",
    locale: "zh",
    cadence: "hourly",
    priority: 2,
    tags: ["X", "twitter", "chinese-ai"],
    enabled: true,
    notes: "Khazix — AI 写作 / 长文观察",
  },
  {
    id: "x-yuchenj",
    name: { en: "X · @Yuchenj_UW", zh: "X · @Yuchenj_UW" },
    url: "https://x.com/Yuchenj_UW",
    kind: "x-api",
    group: "social",
    locale: "multi",
    cadence: "hourly",
    priority: 2,
    tags: ["X", "twitter", "infrastructure"],
    enabled: true,
    notes: "Yuchen Jin (Hyperbolic) — 推理基础设施、模型部署",
  },
  {
    id: "x-op7418",
    name: { en: "X · @op7418", zh: "X · @op7418（歸藏）" },
    url: "https://x.com/op7418",
    kind: "x-api",
    group: "social",
    locale: "zh",
    cadence: "hourly",
    priority: 2,
    tags: ["X", "twitter", "tutorial"],
    enabled: true,
    notes: "歸藏 — AI 工具 / 教程 / 案例分享",
  },
  // Vendor-official X accounts: product announcements, model releases,
  // researcher highlights. Hourly cadence keeps us on top of launches.
  {
    id: "x-anthropic",
    name: { en: "X · @AnthropicAI", zh: "X · @AnthropicAI" },
    url: "https://x.com/AnthropicAI",
    kind: "x-api",
    group: "vendor-official",
    locale: "en",
    cadence: "hourly",
    priority: 1,
    tags: ["X", "twitter", "Anthropic"],
    enabled: true,
    notes: "Anthropic 官方 — 模型发布、产品更新",
  },
  {
    id: "x-claude",
    name: { en: "X · @claudeai", zh: "X · @claudeai" },
    url: "https://x.com/claudeai",
    kind: "x-api",
    group: "vendor-official",
    locale: "en",
    cadence: "hourly",
    priority: 1,
    tags: ["X", "twitter", "Anthropic", "Claude"],
    enabled: true,
    notes: "Claude 产品账号 — 使用技巧、新功能",
  },
  {
    id: "x-openai",
    name: { en: "X · @OpenAI", zh: "X · @OpenAI" },
    url: "https://x.com/OpenAI",
    kind: "x-api",
    group: "vendor-official",
    locale: "en",
    cadence: "hourly",
    priority: 1,
    tags: ["X", "twitter", "OpenAI"],
    enabled: true,
    notes: "OpenAI 官方 — 模型发布、产品更新",
  },
  {
    id: "bluesky-ai",
    name: { en: "Bluesky · #ai", zh: "Bluesky · #ai" },
    url: "https://bsky.app/hashtag/ai/rss",
    kind: "rss",
    group: "social",
    locale: "en",
    cadence: "hourly",
    priority: 3,
    tags: ["Bluesky"],
    enabled: false,
  },
  {
    id: "reddit-localllama",
    name: { en: "r/LocalLLaMA", zh: "r/LocalLLaMA" },
    url: "https://www.reddit.com/r/LocalLLaMA/.rss",
    kind: "rss",
    group: "social",
    locale: "en",
    cadence: "hourly",
    priority: 2,
    tags: ["Reddit", "open-source"],
    enabled: true,
  },
  {
    id: "zhihu-hotlist",
    name: { en: "Zhihu Hotlist", zh: "知乎热榜" },
    url: "https://rsshub.app/zhihu/hotlist",
    kind: "rsshub",
    group: "social",
    locale: "zh",
    cadence: "hourly",
    priority: 2,
    tags: ["知乎"],
    enabled: true,
  },
  {
    id: "wechat-jiqizhixin-mp",
    name: { en: "机器之心 (WeChat MP)", zh: "机器之心 · 公众号" },
    url: "https://rsshub.app/wechat/officialaccount/机器之心",
    kind: "rsshub",
    group: "social",
    locale: "zh",
    cadence: "daily",
    priority: 2,
    tags: ["微信", "中文"],
    enabled: true,
    notes: "Cookie rotation required",
  },

  // ── Product ──────────────────────────────────────────────────────
  {
    id: "product-hunt-ai",
    name: { en: "Product Hunt · AI", zh: "Product Hunt · AI" },
    url: "https://www.producthunt.com/feed?category=artificial-intelligence",
    kind: "rss",
    group: "product",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["product"],
    enabled: true,
  },
  {
    id: "github-trending",
    name: { en: "GitHub Trending · Python", zh: "GitHub 热门 · Python" },
    url: "https://github.com/trending/python.atom?since=daily",
    kind: "atom",
    group: "product",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["github"],
    enabled: true,
  },
  {
    id: "hf-trending-models",
    name: { en: "HF Trending Models", zh: "HF 趋势模型" },
    url: "https://huggingface.co/api/trending",
    kind: "api",
    group: "product",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["model"],
    enabled: true,
  },

  // ── Podcast ──────────────────────────────────────────────────────
  {
    id: "dwarkesh",
    name: { en: "Dwarkesh Patel", zh: "Dwarkesh Patel 播客" },
    url: "https://www.dwarkeshpatel.com/feed",
    kind: "rss",
    group: "podcast",
    locale: "en",
    cadence: "weekly",
    priority: 1,
    tags: ["podcast"],
    enabled: true,
  },
  {
    id: "latent-space",
    name: { en: "Latent Space", zh: "Latent Space" },
    url: "https://www.latent.space/feed",
    kind: "rss",
    group: "podcast",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["podcast"],
    enabled: true,
  },
  {
    id: "lex-fridman-yt",
    name: { en: "Lex Fridman (YouTube RSS)", zh: "Lex Fridman 播客" },
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSHZKyawb77ixDdsGog4iWA",
    kind: "atom",
    group: "podcast",
    locale: "en",
    cadence: "weekly",
    priority: 3,
    tags: ["podcast"],
    enabled: true,
  },
  {
    id: "dwarkesh-yt",
    name: { en: "Dwarkesh Patel", zh: "Dwarkesh Patel 访谈" },
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCXl4i9dYBrFOabk0xGmbkRA",
    kind: "atom",
    group: "podcast",
    locale: "en",
    cadence: "weekly",
    priority: 1,
    tags: ["podcast", "interview", "research"],
    enabled: true,
    notes: "Long-form AI research interviews — Dario Amodei, Jeff Dean, Sam Altman, etc. Transcripts via youtube-transcript worker (task #34).",
  },
  {
    id: "thevalley101-yt",
    name: { en: "TheValley101 (硅谷101)", zh: "硅谷101 播客" },
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UChnNjLyx_5rk_iDPQ2BQDQA",
    kind: "atom",
    group: "podcast",
    locale: "zh",
    cadence: "weekly",
    priority: 1,
    tags: ["podcast", "interview"],
    enabled: true,
    notes: "中文长播客 — 深度访谈 Silicon Valley 的 AI 创业者与研究员。Transcripts via youtube-transcript worker (task #34).",
  },
  {
    id: "bestpartners-yt",
    name: { en: "最佳拍档 (BestPartners)", zh: "最佳拍档" },
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCGWYKICLOE8Wxy7q3eYXmPA",
    kind: "atom",
    group: "podcast",
    locale: "zh",
    cadence: "weekly",
    priority: 1,
    tags: ["podcast", "interview"],
    enabled: true,
    notes: "中文 AI 深度视频 — 每期深挖一个 agent / skill / framework。Transcripts via youtube-transcript worker (task #34).",
  },

  // ── Policy ───────────────────────────────────────────────────────
  {
    id: "eu-ai-act",
    name: { en: "EU AI Act", zh: "欧盟 AI 法案" },
    url: "https://artificialintelligenceact.eu/feed/",
    kind: "rss",
    group: "policy",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["regulation"],
    enabled: true,
  },
  {
    id: "nist-ai",
    name: { en: "NIST AI", zh: "美国 NIST AI" },
    url: "https://www.nist.gov/ai",
    kind: "scrape",
    group: "policy",
    locale: "en",
    cadence: "weekly",
    priority: 3,
    tags: ["regulation", "standards"],
    enabled: false,
  },

  // ── Market ───────────────────────────────────────────────────────
  {
    id: "crunchbase-ai",
    name: { en: "Crunchbase AI Funding Digest", zh: "Crunchbase · AI 融资" },
    url: "internal://crunchbase",
    kind: "api",
    group: "market",
    locale: "en",
    cadence: "daily",
    priority: 3,
    tags: ["funding"],
    enabled: false,
    notes: "Paid API — disabled by default",
  },

  // ═══════════════════════════════════════════════════════════════
  // Expanded catalog (2026-04-16): curated from RSS-Renaissance
  // awesome-blogCN-feeds / awesome-newsCN-feeds, wechat2rss.xlab.app,
  // weekend-project-space/top-rss-list + user ask for macro/geopolitics.
  // All URLs verified with HTTP 200 at time of commit.
  // ═══════════════════════════════════════════════════════════════

  // ── High-priority personal blogs ────────────────────────────────
  {
    id: "yage-computing-life",
    name: { en: "Computing Life (鸭哥 / grapeot)", zh: "Computing Life · 鸭哥" },
    url: "https://yage.ai/feeds/atom.xml",
    kind: "atom",
    group: "research",
    locale: "zh",
    cadence: "weekly",
    priority: 1,
    tags: ["system-design", "深度分析", "independent"],
    enabled: true,
    notes: "P0 per user — deep technical commentary, rare signal",
  },
  {
    id: "yage-share",
    name: {
      en: "Computing Life · Share (鸭哥 research reports)",
      zh: "Computing Life · Share · 鸭哥调研",
    },
    url: "https://yage.ai/share/feed.xml",
    kind: "rss",
    group: "research",
    locale: "zh",
    cadence: "daily",
    priority: 1,
    tags: ["research", "深度分析", "ai-generated"],
    enabled: true,
    notes: "P0 per user — 鸭哥's research-report feed (self-described 100% AI-generated)",
  },
  {
    id: "ruanyifeng-blog",
    name: { en: "Ruan YiFeng's Weblog", zh: "阮一峰的网络日志" },
    url: "https://feeds.feedburner.com/ruanyifeng",
    kind: "rss",
    group: "research",
    locale: "zh",
    cadence: "weekly",
    priority: 1,
    tags: ["tech-weekly", "independent"],
    enabled: true,
  },
  {
    id: "coolshell-cn",
    name: { en: "CoolShell (左耳朵耗子)", zh: "酷壳 · 左耳朵耗子" },
    url: "https://coolshell.cn/feed",
    kind: "rss",
    group: "research",
    locale: "zh",
    cadence: "weekly",
    priority: 2,
    tags: ["systems", "architecture"],
    enabled: true,
  },

  // ── Chinese AI media via WeChat2RSS (bypass of rsshub.app) ──────
  {
    id: "jiqizhixin-w2r",
    name: { en: "Synced (机器之心) · WeChat", zh: "机器之心 · 公众号" },
    url: "https://wechat2rss.xlab.app/feed/51e92aad2728acdd1fda7314be32b16639353001.xml",
    kind: "rss",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 1,
    tags: ["ai", "research", "中文"],
    enabled: true,
    notes: "Working alternative to broken jiqizhixin rsshub",
  },
  {
    id: "xinzhiyuan-w2r",
    name: { en: "AI Era (新智元) · WeChat", zh: "新智元 · 公众号" },
    url: "https://wechat2rss.xlab.app/feed/ede30346413ea70dbef5d485ea5cbb95cca446e7.xml",
    kind: "rss",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 1,
    tags: ["ai", "startup", "中文"],
    enabled: true,
  },
  {
    id: "qbitai-w2r",
    name: { en: "QbitAI (量子位) · WeChat", zh: "量子位 · 公众号" },
    url: "https://wechat2rss.xlab.app/feed/7131b577c61365cb47e81000738c10d872685908.xml",
    kind: "rss",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 1,
    tags: ["ai", "industry", "中文"],
    enabled: true,
    notes: "Working alternative to broken qbitai rsshub",
  },
  {
    id: "tencent-tech-w2r",
    name: { en: "Tencent Technology · WeChat", zh: "腾讯技术工程 · 公众号" },
    url: "https://wechat2rss.xlab.app/feed/9685937b45fe9c7a526dbc32e4f24ba879a65b9a.xml",
    kind: "rss",
    group: "vendor-official",
    locale: "zh",
    cadence: "weekly",
    priority: 2,
    tags: ["cloud", "infrastructure", "ml-platform"],
    enabled: true,
  },
  {
    id: "alibaba-tech-w2r",
    name: { en: "Alibaba Technology · WeChat", zh: "阿里技术 · 公众号" },
    url: "https://wechat2rss.xlab.app/feed/6e1f9b775f7a5841ac1a94310f0478b45a02ec01.xml",
    kind: "rss",
    group: "vendor-official",
    locale: "zh",
    cadence: "weekly",
    priority: 2,
    tags: ["cloud", "database", "ai-infra"],
    enabled: true,
  },

  // ── Direct-feed Chinese media (bypass of rsshub.app) ────────────
  {
    id: "36kr-direct",
    name: { en: "36Kr (direct RSS)", zh: "36 氪 · 直链" },
    url: "https://36kr.com/feed",
    kind: "rss",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 1,
    tags: ["startup", "funding", "中文"],
    enabled: true,
    notes: "Working alternative to broken 36kr-ai rsshub",
  },
  {
    id: "huxiu-feedx",
    name: { en: "Huxiu (via FeedX)", zh: "虎嗅 · FeedX" },
    url: "https://feedx.net/rss/huxiu.xml",
    kind: "rss",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 1,
    tags: ["business", "analysis", "中文"],
    enabled: true,
    notes: "Working alternative to broken huxiu-ai rsshub",
  },
  {
    id: "sspai-direct",
    name: { en: "Sspai (direct RSS)", zh: "少数派 · 直链" },
    url: "https://sspai.com/feed",
    kind: "rss",
    group: "newsletter",
    locale: "zh",
    cadence: "daily",
    priority: 2,
    tags: ["tools", "productivity", "中文"],
    enabled: true,
    notes: "Working alternative to broken sspai-matrix rsshub",
  },

  // ── Macro economy + geopolitics (AI/tech intersection) ──────────
  {
    id: "nytimes-cn-feedx",
    name: { en: "New York Times Chinese", zh: "纽约时报中文网" },
    url: "https://feedx.net/rss/nytimes.xml",
    kind: "rss",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 2,
    tags: ["geopolitics", "us-china", "tech-policy"],
    enabled: true,
  },
  {
    id: "thepaper-feedx",
    name: { en: "The Paper (澎湃新闻) · FeedX", zh: "澎湃新闻 · FeedX" },
    url: "https://feedx.net/rss/thepaper.xml",
    kind: "rss",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 2,
    tags: ["policy", "regulation", "中文"],
    enabled: true,
  },
  {
    id: "jiemoren-macro-w2r",
    name: {
      en: "Ping Lan Yu Yan (凭栏欲言) · WeChat",
      zh: "凭栏欲言 · 公众号",
    },
    url: "https://wechat2rss.xlab.app/feed/01c05fce74822ac6f30656f22e0ca542dfb7c8c0.xml",
    kind: "rss",
    group: "newsletter",
    locale: "zh",
    cadence: "daily",
    priority: 2,
    tags: ["macro", "policy", "economics"],
    enabled: true,
  },
  {
    id: "bloomberg-tech",
    name: { en: "Bloomberg Technology", zh: "彭博科技" },
    url: "https://feeds.bloomberg.com/technology/news.rss",
    kind: "rss",
    group: "media",
    locale: "en",
    cadence: "daily",
    priority: 1,
    tags: ["business", "ai-news", "funding"],
    enabled: true,
  },
  {
    id: "ft-technology",
    name: { en: "Financial Times · Technology", zh: "FT · 科技" },
    url: "https://www.ft.com/technology?format=rss",
    kind: "rss",
    group: "media",
    locale: "en",
    cadence: "daily",
    priority: 1,
    tags: ["tech-policy", "business", "regulation"],
    enabled: true,
  },
  {
    id: "sinocism",
    name: { en: "Sinocism (Bill Bishop)", zh: "Sinocism · 比尔·毕晓普" },
    url: "https://sinocism.com/feed",
    kind: "rss",
    group: "newsletter",
    locale: "en",
    cadence: "daily",
    priority: 1,
    tags: ["china-policy", "geopolitics", "us-china"],
    enabled: true,
    notes: "Bill Bishop's newsletter — highest signal on China-tech policy",
  },
  {
    id: "rest-of-world",
    name: { en: "Rest of World", zh: "Rest of World · 全球科技" },
    url: "https://www.rest-of-world.com/feed/rss/",
    kind: "rss",
    group: "media",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["global-tech", "non-us", "policy"],
    enabled: true,
  },

  // ── Additional research feeds ───────────────────────────────────
  {
    id: "arxiv-cs-lg",
    name: { en: "arXiv · cs.LG", zh: "arXiv · cs.LG" },
    url: "https://rss.arxiv.org/rss/cs.LG",
    kind: "atom",
    group: "research",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["arxiv", "ml"],
    enabled: true,
  },
  {
    id: "hf-papers-takara",
    name: {
      en: "HuggingFace Papers (takara mirror)",
      zh: "HuggingFace 论文 · takara 镜像",
    },
    url: "https://papers.takara.ai/api/feed",
    kind: "rss",
    group: "research",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["paper", "digest"],
    enabled: true,
    notes: "Community-run daily-papers bridge; easier than the HF scrape",
  },
];

export function sourcesByGroup() {
  const byGroup = new Map<string, Source[]>();
  for (const s of sourceCatalog) {
    if (!byGroup.has(s.group)) byGroup.set(s.group, []);
    byGroup.get(s.group)!.push(s);
  }
  return byGroup;
}
