import type { Source } from "@/lib/types";

export const sourceCatalog: Source[] = [
  // ── Vendor official ─────────────────────────────────────────────
  {
    id: "anthropic-news",
    name: { en: "Anthropic News", zh: "Anthropic 官方动态" },
    url: "https://www.anthropic.com/news",
    kind: "scrape",
    group: "vendor-official",
    locale: "en",
    cadence: "daily",
    priority: 1,
    tags: ["Anthropic", "product", "research"],
    enabled: true,
  },
  {
    id: "openai-news",
    name: { en: "OpenAI Blog", zh: "OpenAI 博客" },
    url: "https://openai.com/news/rss.xml",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "daily",
    priority: 1,
    tags: ["OpenAI", "product", "research"],
    enabled: true,
  },
  {
    id: "google-deepmind",
    name: { en: "Google DeepMind Blog", zh: "DeepMind 博客" },
    url: "https://deepmind.google/discover/blog/rss.xml",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "weekly",
    priority: 1,
    tags: ["DeepMind", "research"],
    enabled: true,
  },
  {
    id: "google-research",
    name: { en: "Google Research Blog", zh: "Google 研究院" },
    url: "https://research.google/blog/rss/",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["Google", "research"],
    enabled: true,
  },
  {
    id: "meta-ai",
    name: { en: "Meta AI Blog", zh: "Meta AI 博客" },
    url: "https://ai.meta.com/blog/rss/",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["Meta", "research"],
    enabled: true,
  },
  {
    id: "microsoft-ai",
    name: { en: "Microsoft AI Blog", zh: "微软 AI 博客" },
    url: "https://blogs.microsoft.com/ai/feed/",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["Microsoft"],
    enabled: true,
  },
  {
    id: "nvidia-blog",
    name: { en: "NVIDIA Blog", zh: "NVIDIA 博客" },
    url: "https://blogs.nvidia.com/feed/",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["NVIDIA", "hardware"],
    enabled: true,
  },
  {
    id: "huggingface-blog",
    name: { en: "Hugging Face Blog", zh: "Hugging Face 博客" },
    url: "https://huggingface.co/blog/feed.xml",
    kind: "rss",
    group: "vendor-official",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["HuggingFace", "open-source"],
    enabled: true,
  },
  {
    id: "xiaomi-research",
    name: { en: "Xiaomi AI Lab", zh: "小米 AI 实验室" },
    url: "https://rsshub.app/xiaomi/ai",
    kind: "rsshub",
    group: "vendor-official",
    locale: "zh",
    cadence: "weekly",
    priority: 1,
    tags: ["小米", "model"],
    enabled: true,
  },
  {
    id: "deepseek-hf",
    name: { en: "DeepSeek (HuggingFace)", zh: "深度求索 (HF)" },
    url: "https://huggingface.co/deepseek-ai",
    kind: "scrape",
    group: "vendor-official",
    locale: "multi",
    cadence: "daily",
    priority: 1,
    tags: ["DeepSeek", "open-source"],
    enabled: true,
  },
  {
    id: "qwen-hf",
    name: { en: "Qwen (Alibaba)", zh: "通义千问" },
    url: "https://huggingface.co/Qwen",
    kind: "scrape",
    group: "vendor-official",
    locale: "multi",
    cadence: "daily",
    priority: 1,
    tags: ["Alibaba", "open-source"],
    enabled: true,
  },

  // ── Media ────────────────────────────────────────────────────────
  {
    id: "hn-frontpage",
    name: { en: "Hacker News Frontpage", zh: "Hacker News 首页" },
    url: "https://hnrss.org/frontpage",
    kind: "rss",
    group: "media",
    locale: "en",
    cadence: "hourly",
    priority: 1,
    tags: ["tech", "community"],
    enabled: true,
  },
  {
    id: "techcrunch-ai",
    name: { en: "TechCrunch AI", zh: "TechCrunch AI" },
    url: "https://techcrunch.com/category/artificial-intelligence/feed/",
    kind: "rss",
    group: "media",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["news"],
    enabled: true,
  },
  {
    id: "verge-ai",
    name: { en: "The Verge · AI", zh: "The Verge · AI" },
    url: "https://www.theverge.com/rss/ai-artificial-intelligence/index.xml",
    kind: "rss",
    group: "media",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["news"],
    enabled: true,
  },
  {
    id: "mit-techreview",
    name: { en: "MIT Technology Review", zh: "MIT 科技评论" },
    url: "https://www.technologyreview.com/feed/",
    kind: "rss",
    group: "media",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["analysis"],
    enabled: true,
  },
  {
    id: "36kr-ai",
    name: { en: "36kr AI Channel", zh: "36 氪 · AI 频道" },
    url: "https://rsshub.app/36kr/news/35",
    kind: "rsshub",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 1,
    tags: ["news", "中文"],
    enabled: true,
  },
  {
    id: "huxiu-ai",
    name: { en: "Huxiu · AI", zh: "虎嗅 · AI" },
    url: "https://rsshub.app/huxiu/channel/ai",
    kind: "rsshub",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 2,
    tags: ["中文"],
    enabled: true,
  },
  {
    id: "sspai-matrix",
    name: { en: "Sspai Matrix", zh: "少数派 Matrix" },
    url: "https://rsshub.app/sspai/matrix",
    kind: "rsshub",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 2,
    tags: ["中文"],
    enabled: true,
  },
  {
    id: "jiqizhixin",
    name: { en: "Synced (jiqizhixin)", zh: "机器之心" },
    url: "https://rsshub.app/jiqizhixin",
    kind: "rsshub",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 1,
    tags: ["中文", "research"],
    enabled: true,
  },
  {
    id: "qbitai",
    name: { en: "QbitAI", zh: "量子位" },
    url: "https://rsshub.app/qbitai",
    kind: "rsshub",
    group: "media",
    locale: "zh",
    cadence: "daily",
    priority: 1,
    tags: ["中文"],
    enabled: true,
  },

  // ── Newsletter ──────────────────────────────────────────────────
  {
    id: "bensbites",
    name: { en: "Ben's Bites", zh: "Ben's Bites" },
    url: "https://www.bensbites.com/feed",
    kind: "rss",
    group: "newsletter",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["newsletter"],
    enabled: true,
  },
  {
    id: "thebatch",
    name: { en: "The Batch (Andrew Ng)", zh: "The Batch (吴恩达)" },
    url: "https://www.deeplearning.ai/the-batch/feed/",
    kind: "rss",
    group: "newsletter",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["newsletter"],
    enabled: true,
  },
  {
    id: "importai",
    name: { en: "Import AI (Jack Clark)", zh: "Import AI" },
    url: "https://jack-clark.net/feed/",
    kind: "rss",
    group: "newsletter",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["policy", "newsletter"],
    enabled: true,
  },

  // ── Research ────────────────────────────────────────────────────
  {
    id: "arxiv-cs-ai",
    name: { en: "arXiv · cs.AI", zh: "arXiv · cs.AI" },
    url: "http://export.arxiv.org/api/query?search_query=cat:cs.AI&sortBy=submittedDate&sortOrder=descending",
    kind: "atom",
    group: "research",
    locale: "en",
    cadence: "daily",
    priority: 1,
    tags: ["arxiv", "paper"],
    enabled: true,
  },
  {
    id: "arxiv-cs-cl",
    name: { en: "arXiv · cs.CL", zh: "arXiv · cs.CL" },
    url: "http://export.arxiv.org/api/query?search_query=cat:cs.CL&sortBy=submittedDate&sortOrder=descending",
    kind: "atom",
    group: "research",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["arxiv", "nlp"],
    enabled: true,
  },
  {
    id: "huggingface-papers",
    name: { en: "HuggingFace Papers", zh: "HuggingFace 每日论文" },
    url: "https://huggingface.co/papers",
    kind: "scrape",
    group: "research",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["paper", "digest"],
    enabled: true,
  },
  {
    id: "paperswithcode",
    name: { en: "Papers With Code Trending", zh: "Papers With Code 热门" },
    url: "https://paperswithcode.com/latest",
    kind: "scrape",
    group: "research",
    locale: "en",
    cadence: "daily",
    priority: 3,
    tags: ["paper"],
    enabled: false,
  },

  // ── Social ───────────────────────────────────────────────────────
  {
    id: "x-ai-watchlist",
    name: { en: "X Watchlist (curated handles)", zh: "X 监控（重点账号）" },
    url: "internal://x-watchlist",
    kind: "api",
    group: "social",
    locale: "multi",
    cadence: "hourly",
    priority: 1,
    tags: ["X", "twitter"],
    enabled: true,
    notes: "Uses Apify x-scraper actor OR X API v2 with per-handle budget.",
  },
  {
    id: "bluesky-ai",
    name: { en: "Bluesky · #ai", zh: "Bluesky · #ai" },
    url: "https://bsky.app/hashtag/ai/rss",
    kind: "rss",
    group: "social",
    locale: "en",
    cadence: "hourly",
    priority: 3,
    tags: ["Bluesky"],
    enabled: false,
  },
  {
    id: "reddit-localllama",
    name: { en: "r/LocalLLaMA", zh: "r/LocalLLaMA" },
    url: "https://www.reddit.com/r/LocalLLaMA/.rss",
    kind: "rss",
    group: "social",
    locale: "en",
    cadence: "hourly",
    priority: 2,
    tags: ["Reddit", "open-source"],
    enabled: true,
  },
  {
    id: "zhihu-hotlist",
    name: { en: "Zhihu Hotlist", zh: "知乎热榜" },
    url: "https://rsshub.app/zhihu/hotlist",
    kind: "rsshub",
    group: "social",
    locale: "zh",
    cadence: "hourly",
    priority: 2,
    tags: ["知乎"],
    enabled: true,
  },
  {
    id: "wechat-jiqizhixin-mp",
    name: { en: "机器之心 (WeChat MP)", zh: "机器之心 · 公众号" },
    url: "https://rsshub.app/wechat/officialaccount/机器之心",
    kind: "rsshub",
    group: "social",
    locale: "zh",
    cadence: "daily",
    priority: 2,
    tags: ["微信", "中文"],
    enabled: true,
    notes: "Cookie rotation required",
  },

  // ── Product ──────────────────────────────────────────────────────
  {
    id: "product-hunt-ai",
    name: { en: "Product Hunt · AI", zh: "Product Hunt · AI" },
    url: "https://www.producthunt.com/feed?category=artificial-intelligence",
    kind: "rss",
    group: "product",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["product"],
    enabled: true,
  },
  {
    id: "github-trending",
    name: { en: "GitHub Trending · Python", zh: "GitHub 热门 · Python" },
    url: "https://github.com/trending/python.atom?since=daily",
    kind: "atom",
    group: "product",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["github"],
    enabled: true,
  },
  {
    id: "hf-trending-models",
    name: { en: "HF Trending Models", zh: "HF 趋势模型" },
    url: "https://huggingface.co/api/trending",
    kind: "api",
    group: "product",
    locale: "en",
    cadence: "daily",
    priority: 2,
    tags: ["model"],
    enabled: true,
  },

  // ── Podcast ──────────────────────────────────────────────────────
  {
    id: "dwarkesh",
    name: { en: "Dwarkesh Patel", zh: "Dwarkesh Patel 播客" },
    url: "https://www.dwarkeshpatel.com/feed",
    kind: "rss",
    group: "podcast",
    locale: "en",
    cadence: "weekly",
    priority: 1,
    tags: ["podcast"],
    enabled: true,
  },
  {
    id: "latent-space",
    name: { en: "Latent Space", zh: "Latent Space" },
    url: "https://www.latent.space/feed",
    kind: "rss",
    group: "podcast",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["podcast"],
    enabled: true,
  },
  {
    id: "lex-fridman-yt",
    name: { en: "Lex Fridman (YouTube RSS)", zh: "Lex Fridman 播客" },
    url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCSHZKyawb77ixDdsGog4iWA",
    kind: "atom",
    group: "podcast",
    locale: "en",
    cadence: "weekly",
    priority: 3,
    tags: ["podcast"],
    enabled: true,
  },

  // ── Policy ───────────────────────────────────────────────────────
  {
    id: "eu-ai-act",
    name: { en: "EU AI Act", zh: "欧盟 AI 法案" },
    url: "https://artificialintelligenceact.eu/feed/",
    kind: "rss",
    group: "policy",
    locale: "en",
    cadence: "weekly",
    priority: 2,
    tags: ["regulation"],
    enabled: true,
  },
  {
    id: "nist-ai",
    name: { en: "NIST AI", zh: "美国 NIST AI" },
    url: "https://www.nist.gov/ai",
    kind: "scrape",
    group: "policy",
    locale: "en",
    cadence: "weekly",
    priority: 3,
    tags: ["regulation", "standards"],
    enabled: false,
  },

  // ── Market ───────────────────────────────────────────────────────
  {
    id: "crunchbase-ai",
    name: { en: "Crunchbase AI Funding Digest", zh: "Crunchbase · AI 融资" },
    url: "internal://crunchbase",
    kind: "api",
    group: "market",
    locale: "en",
    cadence: "daily",
    priority: 3,
    tags: ["funding"],
    enabled: false,
    notes: "Paid API — disabled by default",
  },
];

export function sourcesByGroup() {
  const byGroup = new Map<string, Source[]>();
  for (const s of sourceCatalog) {
    if (!byGroup.has(s.group)) byGroup.set(s.group, []);
    byGroup.get(s.group)!.push(s);
  }
  return byGroup;
}
